
baseurl = "https://blog.whitescent.top"
languageCode = "zh-cn"
paginate = 5
title = "WhiteScent"
DefaultContentLanguage = "zh-cn"

hasCJKLanguage = false

disqusShortname = "hugo-theme-stack"

[languages]
    [languages.zh-cn]
        contentDir = "content/zh-cn"
        languageName = "中文（简体）"
        weight = 1
    [languages.en]
        contentDir = "content/en"
        languageName = "English"
        weight = 2