# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/whitescent"

[social.params]
icon = "brand-github"

[[social]]
identifier = "soundcloud"
name = "Soundcloud"
url = "https://soundcloud.com/cloudrealm"

[social.params]
icon = "brand-soundcloud"

[[social]]
identifier = "steam"
name = "Steam"
url = "https://steamcommunity.com/id/rouxzed/"

[social.params]
icon = "brand-steam"

[[social]]
identifier = "rss"
name = "rss"
url = "https://blog.whitescent.top/index.xml"

[social.params]
icon = "brand-rss"
